### PR TITLE
Add Chrome & Firefox profile demanglers

### PR DESCRIPTION
**Pull request by j-f1**
I’d appreciate any feedback about the wording or the tool!

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]
I primarily use Firefox and don't have experience with Chrome devtools, but this looks great 👍

**Comment by MaxDesiatov** [comment]
I've sent you a contributor invite, so feel free to merge 🙂

**Comment by j-f1** [comment]
> I primarily use Firefox and don't have experience with Chrome devtools, but this looks great 👍

Updated!

**Comment by MaxDesiatov** [comment]
This is probably not the right place to report issues, but I tried to upload this to the Firefox version and got `RuntimeError: name is null`.

[profile.json.zip](https://github.com/swiftwasm/awesome-swiftwasm/files/5012757/profile.json.zip)

**Comment by j-f1** [comment]
Oops, didn’t realize the names could be null. Fixed!

**Pull request merged**
